# Generated by Django 5.0.4 on 2024-04-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='nickname',
            field=models.CharField(default='Anonymous', max_length=10),
        ),
    ]
